<?php

use Drupal\Component\Utility\String;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for user_login_form().
 */
/*function user_restrictions_form_user_login_form_alter(&$form, &$form_state) {
	$form['#validate'][] = 'user_restrictions_validate';
}*/

/**
 * Implements hook_form_FORM_ID_alter() for user_register_form().
 */
/*function user_restrictions_form_user_register_form_alter(&$form, &$form_state) {
	$form['#validate'][] = 'user_restrictions_validate';
}*/

/**
 * Implements hook_form_FORM_ID_alter() for user_form().
 */
function password_policy_form_user_form_alter(&$form, &$form_state) {
	/**
	 * Use cases:
	 * -Add User - how do we know which role? this should come first with an AJAX on change
	 */
	//dpm($form);
	//$form['#validate'][] = 'user_restrictions_validate';

	//dpq($form_state);

	//user interface changes
	//TODO - Consider hiding Password Strength indicator and Password Recommendations
	$form['account']['roles']['#weight'] = '0';
	$form['account']['mail']['#weight'] = '1';
	$form['account']['name']['#weight'] = '2';
	$form['account']['status']['#weight'] = '5';
	$form['account']['notify']['#weight'] = '6';

	//update password field
	$form['account']['pass']['#title'] = 'Password';
	//TODO - Removing password confirm (does not have any AJAX call) causes error on AJAX
	$form['account']['pass']['#type'] = 'password';
	$form['account']['pass']['#weight'] = '3';

	$form['account']['password_policy_status'] = array(
		'#title' => 'Password policies',
		'#type' => 'table',
		'#header' => array(t('Status'), t('Constraint')),
		'#empty' => t('There are no constraints for the selected user roles'),
		'#weight' => '4',
		'#prefix' => '<div id="password-policy-status">',
		'#suffix' => '</div>',
		'#rows' => _password_policy_constraints_table($form, $form_state),
	);

	//set ajax changes
	$form['account']['roles']['#ajax'] = array(
		'event' => 'change',
		'callback' => '_password_policy_check_constraints',
		'method' => 'replace',
		'wrapper' => 'password-policy-status',
	);

	$form['account']['pass']['#ajax'] = array(
		'event' => 'change',
		'callback' => '_password_policy_check_constraints',
		'method' => 'replace',
		'wrapper' => 'password-policy-status',
	);
}

/**
 * AJAX callback for user form
 */
function _password_policy_check_constraints($form, $form_state) {
	return $form['account']['password_policy_status'];
}

/**
 * AJAX callback for user form
 */
function _password_policy_constraints_table($form, $form_state) {
	//FAKE DATA
	$table_rows = array(
		array(
			'constraint' => 'Minimum of 20 characters',
			'status' => 'Pass',
		),
		array(
			'constraint' => 'Must contain two special characters '.time(),
			'status' => 'Fail',
		),
	);

	//get constraints for selected roles
	//
	//$user_constraints = array();
	//foreach($roles as $role){
	//  $role_constraints = _password_policy_get_constraints_by_role($rid);
	//  $user_constraints = array_merge($user_constraints, $role_constraints);
	//}
	//
	//verify and display password for constraints
	//$table_rows = array();
	//foreach($user_constraints as $user_constraint){
	//  $constraint = new $user_constraint();
	//	$table_row = array('constraint' => $constraint->message);
	//	if(!$constraint->validate($form_state->getValue('pass'))){
	//		$table_row['status'] = 'Fail';
	//	} else {
	//		$table_row['status'] = 'Pass';
	//	}
	//	$table_rows[] = $table_row;
	//}

	//if no role, show default message
	return $table_rows;
}

/**
 *
 */